version: "3.8"

services:
  frontend:
    image: YOUR_DOCKERHUB_USERNAME/frontend:latest
    container_name: frontend
    restart: always

  backend:
    image: YOUR_DOCKERHUB_USERNAME/backend:latest
    container_name: backend
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data: